#!/bin/sh

# get my extern IP address
#
# or http://checkip.amazonaws.com/
#

if [ "$1" = "" ]
then
	curl -s https://ipinfo.io/ip
elif [ "$1" = "-a" ]
then
	curl -s https://ipinfo.io/
else
	echo `basename $0` [-a]
fi
